sudo snap connect steam:audio-record
sudo snap connect steam:bluez
sudo snap connect steam:fuse-support
sudo snap connect steam:hardware-observe
sudo snap connect steam:joystick
sudo snap connect steam:mount-observe
sudo snap connect steam:network-control
sudo snap connect steam:dot-local-share-applications
sudo snap connect steam:dot-local-share-icons
sudo snap connect steam:dot-local-share-steam
sudo snap connect steam:user-fex-config
sudo snap connect steam:process-control
sudo snap connect steam:removable-media
sudo snap connect steam:steam-support
sudo snap connect steam:system-observe
sudo snap connect steam:uinput
sudo snap connect steam:network-observe
sudo snap connect steam:gaming-graphics-core24 gaming-graphics-core24
sudo snap connections steam
