#!/bin/bash

# Gamescope runs an xwayland server, and tells games to render into that.
# Normally an app running an xwayland server binds to a free socket in the
# global /tmp/.X11-unix/ space, so other apps can find it to render into it.
# These are read-only unless the snap asks for an x11 socket.
#
# Naively, steam snap would need to ask for an x11 socket slot,
# which requires manual review + approval
# (https://forum.snapcraft.io/t/x11-plug-and-slot-needing-manual-review/8693/2)
#
# However, the gamescope-xwayland server is just for the game running under
# the gamescope command, so we can instead make a private x11 socket dir
# for it instead of using the global /tmp/.X11 space.
# This keeps the steam+gamescope snap all well encapsulated from userspace.
#
# Ideally, wlroots would take an input for the X11 socket, and then gamescope
# could make a private file and pass it. But instead wlroots hardcodes the
# socket dir:
# https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/xwayland/sockets.c
#
# So instead, we make a private x11 dir inside the snap-space

echo "Running gamescope in bubblewrap to create private x11 socket"

GAMESCOPE="${SNAP}/usr/games/gamescope"
exec bwrap --dev-bind / / --perms 1777 --tmpfs /tmp/.X11-unix -- \
  ${GAMESCOPE} "$@"