#!/usr/bin/python3

import os

NVIDIA_ENV = "__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only"

def main():
    lspci = os.popen("lspci | grep VGA").read()
    gpus = lspci.splitlines()
    env_string = ""

    for gpu in gpus:
        split = gpu.split(" VGA compatible controller: ")
        pci = f"pci-0000_{split[0]}"\
            .replace(":", "_")\
            .replace(".", "_")\

        if "nvidia" in split[1].lower():
            env_string = f"DRI_PRIME={pci} {NVIDIA_ENV}"
            break

        elif "amd" in split[1].lower():
            env_string = f"DRI_PRIME={pci}"
            break

    print(env_string)


if __name__ == "__main__":
    main()
