#!/bin/bash

nvidia_version=$(modinfo /usr/lib/modules/$(uname -r)/kernel/nvidia*/nvidia.ko 2> /dev/null | grep -m 1 "^version:" | sed "s/version:\s*//")
if [[ ! $nvidia_version ]]; then
    nvidia_version=$(modinfo /usr/lib/modules/$(uname -r)/updates/dkms/nvidia.ko 2> /dev/null | grep -m 1 "^version:" | sed "s/version:\s*//")
fi

if [[ $nvidia_version ]]; then
    nvidia_version_major=$(echo $nvidia_version | sed "s/\..*//")
    echo "Found NVIDIA version: $nvidia_version"

    if [[ -f "/var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.$nvidia_version" ]]\
            && [[ ! -f "/var/lib/snapd/hostfs/usr/lib/i386-linux-gnu/libnvidia-glcore.so.$nvidia_version" ]]; then
        echo "NVIDIA 32-bit libraries not found"
        title="32-bit NVIDIA libraries not found"
        text="<b>32-bit NVIDIA driver files were not found on your host system.</b>
It is recommended that you install them for the best experience.

See <a href='https://github.com/canonical/steam-snap/wiki/FAQ#32-bit-driver'>https://github.com/canonical/steam-snap/wiki/FAQ#32-bit-driver</a> for more info.

To install, run:<tt>
    sudo dpkg --add-architecture i386
    sudo apt update
    sudo apt install libnvidia-gl-$nvidia_version_major:i386</tt>"
        yad --title "$title" --text "$text" --button gtk-ok:0 --center --on-top --selectable-labels
    fi
fi
