#!/usr/bin/python3

import os
import sys
import webbrowser
import argparse
from collections import defaultdict

DISCUSSION_URL = "https://github.com/canonical/steam-snap/discussions/new?category=game-reports"
WIKI_URL = "https://github.com/canonical/steam-snap/wiki/Troubleshooting#submitting-a-game-report"

BODY_SUFFIX = "<!--Copy error logs from Steam/the game itself below-->"

def default():
    return "ERROR"

def dict_to_string(d, n = 0):
    """Convert a dict to yaml-like string."""
    s = ""
    for key in d:
        line = f"{'    ' * n}{key}: "
        if (type(d[key]) is dict):
            line += f"\n{dict_to_string(d[key], n + 1)}"
        else:
            line += f"{' ' * (24 - len(line))}{d[key]}\n"
        s += line
    return s

def gather_data():
    """Gathers system information, returning a data object."""
    data = {}

    # /etc/os-release
    os_release = defaultdict(default)
    os_release_lookup = [
        "/var/lib/snapd/hostfs/etc/os-release", # system-observe host os-release
        "/etc/os-release",                      # usual system os-release
    ]

    for path in os_release_lookup:
        try:
            with open(path, "r") as reader:
                for line in reader:
                    line = line.strip()
                    if (not line): continue

                    key, val = line.split("=", 1)
                    os_release[key] = val
            break
        except FileNotFoundError:
            continue

    if (args.verbose):
        data["os_release"] = dict(os_release)
    else:
        data["os_release"] = {
            "name": os_release["NAME"],
            "version": os_release["VERSION"]
        }

    # snap info
    data["snap_info"] = {
        "steam_revision": os.environ.get("SNAP_REVISION"),
        "snapd_revision": os.popen("readlink /snap/snapd/current").read().strip()
    }

    # lspci
    lspci = defaultdict(default)
    for line in os.popen("lspci | grep -E '(VGA)|(3D controller)'").read().split("\n"):
        line = line.strip()
        if (not line): continue
        key, val = line.split(" ", 1)
        val = val.strip()\
            .removeprefix("VGA compatible controller: ")\
            .removeprefix("3D controller: ")
        lspci[key.strip()] = val

    data["lspci"] = dict(lspci)

    # glxinfo -B
    glxinfo = defaultdict(default)
    for line in os.popen("glxinfo -B").read().split("\n"):
        line = line.strip()
        if (not line): continue
        key, val = line.split(":", 1)
        glxinfo[key.strip()] = val.strip()

    if (args.verbose):
        data["glxinfo"] = dict(glxinfo)
    else:
        data["glxinfo"] = {
            "gpu": glxinfo["OpenGL renderer string"],
            "gpu_version": glxinfo["OpenGL core profile version string"]
        }

    # lscpu
    lscpu = defaultdict(default)
    for line in os.popen("lscpu").read().split("\n"):
        line = line.strip()
        if (not line): continue
        key, val = line.split(":", 1)
        lscpu[key.strip()] = val.strip()

    if (args.verbose):
        data["lscpu"] = dict(lscpu)
    else:
        data["lscpu"] = {
            "model_name": lscpu["Model name"]
        }

    # XDG_DESKTOP_SESSION & DESKTOP_SESSION
    data["xdg_current_desktop"] = os.environ.get("XDG_CURRENT_DESKTOP")
    data["desktop_session"] = os.environ.get("DESKTOP_SESSION")

    return data

def submit_data(data):
    """Open web-browser and fill in system information."""
    url = DISCUSSION_URL
    url += f"&title=Report: {args.title.title()}"
    url += f"&body=```\n{dict_to_string(data)}```\n".replace("\n", "%0A")
    url += BODY_SUFFIX
    print("Opening web browser...")
    webbrowser.open_new_tab(url)

# Parse commandline arguments
parser = argparse.ArgumentParser(
    description=f"Visit {WIKI_URL} for more information."
)
parser.add_argument(
    "title",
    help="Title of the game to report, or title of issue category.",
    default="TITLE",
    nargs="?"
)
parser.add_argument(
    "--no-submit", "-n",
    help="Do not open web browser to a new discussion post.",
    const=True,
    action="store_const"
)
parser.add_argument(
    "--verbose", "-v",
    help="Include entire output from data collection.",
    const=True,
    action="store_const"
)
parser.add_argument(
    "--force", "-f",
    help="Skip environment checks and run anyway.",
    const=True,
    action="store_const"
)
args = parser.parse_args()

# Test environment
if (not args.force):
    if (not os.environ.get("SNAP")):
        sys.exit(
            "This script must be ran from inside a Snap environment.\n" +
            "Run `snap run steam.report`."
        )

    if (os.system("snapctl is-connected system-observe")):
        sys.exit(
            "This script relies on the system-observe Snap plug.\n" +
            "Outside of the snap, run `snap connect steam:system-observe`."
        )

    if (os.system("snapctl is-connected hardware-observe")):
        sys.exit(
            "This script relies on the hardware-observe Snap plug.\n" +
            "Outside of the snap, run `snap connect steam:hardware-observe`."
        )

# Gather and submit data
data = gather_data()
print(dict_to_string(data))
if (not args.no_submit):
    submit_data(data)
