name: steam
summary: Launcher for the Steam software distribution service
description: |
  Steam is a software distribution service with an online store, automated
  installation, automatic updates, achievements, SteamCloud synchronized
  savegame and screenshot functionality, and many social features.
adopt-info: steam
grade: stable
confinement: strict
architectures:
  - build-on: amd64
base: core22
compression: lzo
assumes:
  - snapd2.55.4

lint:
  # Snapcraft's `ldd` lint can't handle 32-bit things,
  # So just make it quiet and also make builds a surprising amount faster
  ignore:
    - library:
        - lib/i386-linux-gnu/**
        - usr/lib/i386-linux-gnu/**
        - lib32/**
        - usr/lib32/**

package-repositories:
  - type: apt
    url: http://repo.steampowered.com/steam/
    suites: [stable]
    components: [steam]
    architectures: [amd64, i386]
    key-id: BA1816EF8E75005FCF5E27A1F24AEA9FB05498B7

layout:
  /usr/lib/steam:
    bind: $SNAP/usr/lib/steam
  /usr/share/zenity:
    bind: $SNAP/usr/share/zenity
  # https://discourse.ubuntu.com/t/the-graphics-core20-snap-interface/23000
  /usr/share/libdrm:
    bind: $SNAP/graphics/usr/share/libdrm
  /usr/share/drirc.d:
    bind: $SNAP/graphics/usr/share/drirc.d
  /usr/lib/x86_64-linux-gnu/alsa-lib:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/ld.so.cache:
    bind-file: $SNAP_DATA/etc/ld.so.cache
  /etc/fonts:
    bind: $SNAP/etc/fonts

### !!! ATTENTION - Do not put environment variables like LD_LIBRARY_PATH or graphics ones in the snapcraft.yaml
### under environment! This are handled in the launch script src/desktop-launch, and duplicating them in both makes things confusing.

plugs:
  gaming-mesa:
    interface: content
    target: $SNAP/graphics
    default-provider: gaming-graphics-core22
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes
  dot-local-share-steam:
    interface: personal-files
    write:
      - $HOME/.local/share/Steam
      - $HOME/Steam
  desktop:
    mount-host-font-cache: false
  shmem:
    interface: shared-memory
    private: true

hooks:
  configure:
    plugs:
      - opengl

parts:
  launcher:
    plugin: nil
    source: ./src
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp steam-snap.sh $CRAFT_PART_INSTALL/bin/
      cp desktop-launch $CRAFT_PART_INSTALL/bin/
      cp steamreport $CRAFT_PART_INSTALL/bin/
      cp vulkaninfo $CRAFT_PART_INSTALL/bin/
      cp vkcube $CRAFT_PART_INSTALL/bin/
      cp glxinfo $CRAFT_PART_INSTALL/bin/
      cp glxgears $CRAFT_PART_INSTALL/bin/

  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
    stage:
      # restrict to only audio-related files - you need to ensure
      # that gtk3 is staged for yad to work correctly, to prompt
      # users to connect the alsa plug or proceed with pulseaudio.
      #
      # This helps prevent symbol conflicts in situations where
      # you're using a non-default library, such as those that the
      # gnome-3-34 extension for core18 provides.
      - etc/asound.conf
      - snap/command-chain/alsa-launch
      - usr/bin/yad*
      - usr/lib/*/alsa-lib
      - usr/lib/*/libasound*
      - usr/lib/*/libasyncns*
      - usr/lib/*/libdnsfile*
      - usr/lib/*/libFLAC*
      - usr/lib/*/libjack*
      - usr/lib/*/libpulse*
      - usr/lib/*/libsamplerate*
      - usr/lib/*/libsndfile*
      - usr/lib/*/libspeex*
      - usr/lib/*/libvorbis*
      - usr/lib/*/pulseaudio
      - usr/share/alsa

  ninja:
    plugin: nil
    source: https://github.com/ninja-build/ninja.git
    source-tag: "v1.11.0"
    override-build: |
      rm -rf build
      rm -f ninja
      rm -f ninja_bootstrap
      sed -i 's_^#!/usr/bin/env python$_#!/usr/bin/env python3_g' configure.py
      ./configure.py --bootstrap
      mv ninja ninja_bootstrap
      rm -rf build
      ./ninja_bootstrap
      rm -f ninja_bootstrap
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mv ninja $CRAFT_PART_INSTALL/usr/bin/
    build-packages:
      - python3
    prime:
      - -*

  meson-deps:
    after: [ninja]
    plugin: nil
    source: https://github.com/mesonbuild/meson.git
    source-tag: "0.62.2"
    override-build: |
      python3 -m pip install .
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages
      rm -rf $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/meson*
      python3 -m pip install --target=$CRAFT_PART_INSTALL/usr .
      mv $CRAFT_PART_INSTALL/usr/meson* $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/
      sed -i "s%^#!/usr/bin/python3$%#!/usr/bin/env python3%g" /usr/local/bin/meson
      sed -i "s%^#!/usr/bin/python3$%#!/usr/bin/env python3%g" $CRAFT_PART_INSTALL/usr/bin/meson
    build-packages:
      - python3-pip
    prime:
      - -*

  gamemode:
    after: [meson-deps]
    source: https://github.com/ashuntu/gamemode.git
    source-branch: "add-snap-support"
    plugin: meson
    organize:
      snap/steam/current/usr: usr
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - libsystemd-dev
      - pkg-config
      - libdbus-1-dev
    prime:
      - usr/bin/gamemoderun
      - usr/lib/*/libgamemode*.so.*

  debug-tools:
    plugin: nil
    stage-packages:
      - jq
    prime:
      - usr/bin/jq
      - usr/lib/*/libjq.so*
      - usr/lib/*/libonig.so*

  tests:
    plugin: dump
    source: tests
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/tests
      cp -rp * $CRAFT_PART_INSTALL/tests/

  steam-devices:
    plugin: dump
    source: https://github.com/ValveSoftware/steam-devices.git

  steam:
    plugin: nil
    #source: http://repo.steampowered.com/steam/archive/precise/steam_latest.deb
    build-packages:
      - dpkg-dev
      - dirmngr # Needed for launchpad builds
    stage-packages:
      - steam-launcher
      - steam-libs-amd64
      - steam-libs-i386
      - libappindicator3-1
      - libxcb-dri3-0:amd64
      - libxcb-dri3-0:i386
      - libpci3
      - libvulkan1:i386
      - libvulkan1:amd64
      - libxml2:i386
      - libxml2:amd64
      - libicu70:i386
      - libicu70:amd64
      - zlib1g:i386
      - zlib1g:amd64
      - xdg-utils
      - xdg-user-dirs
      - fontconfig-config
      - fontconfig:i386
      - fontconfig:amd64
      - pciutils
      - lsof
      - locales-all
      - usbutils # Allows finding controllers etc
    override-build: |
      craftctl default
      # Set the snap version from the .deb package version
      craftctl set version=$(dpkg-parsechangelog -l $CRAFT_PART_INSTALL/usr/share/doc/steam-launcher/changelog.all.gz -S Version | sed -e s/1://g)
      # Copy over the icon
      cp $CRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/steam.png $CRAFT_PART_INSTALL/steam.png
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      ln -s ../../steam.png $CRAFT_PART_INSTALL/meta/gui/icon.png
      # Install the desktop file, with the icon field munged
      sed 's|Icon=steam|Icon=${SNAP}/steam.png|g' $CRAFT_PART_INSTALL/usr/share/applications/steam.desktop > $CRAFT_PART_INSTALL/steam.desktop
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/bug
      - -usr/share/gdb
      - -usr/share/emacs*
      - -usr/share/lintian
      - -usr/share/drirc.d
      - -usr/share/vulkan
      - -usr/share/Xsession.d
      - -usr/lib/*/dri
      - -usr/lib/*/vdpau
      - -usr/lib/*/libvkd3d*
      - -usr/lib/*/libvulkan*
      - -usr/lib/*/libVk*
      - -usr/lib/*/libLLVM*
    build-snaps: [core22]
    override-prime: |
      craftctl default
      set -eux
      cp -a /snap/core22/current/usr/lib/i386-linux-gnu/* usr/lib/i386-linux-gnu/

  yaru-skin:
    plugin: nil
    source: https://github.com/ubuntu/yaru-for-steam.git
    source-type: git
    stage-packages:
      - fonts-ubuntu
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/share/Steam/skins
      ./install.py -t $CRAFT_PART_INSTALL/usr/share/Steam/skins -w full -n Yaru
    prime:
      - usr/share/fonts/truetype/ubuntu
      - usr/share/Steam/skins

  cleanup:
    after: [steam]
    plugin: nil
    build-snaps:
      - gaming-graphics-core22/kisak-fresh/candidate
    override-prime: |
      set -eux
      cd /snap/gaming-graphics-core22/current/usr/lib
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/lib/{} \;
      cd /snap/gaming-graphics-core22/current/usr/share
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/share/{} \;


apps:
  steam:
    command-chain: [snap/command-chain/alsa-launch, bin/desktop-launch]
    #command: bin/steam-snap.sh
    command: usr/lib/steam/bin_steam.sh -no-cef-sandbox
    desktop: steam.desktop
    environment:
      HOME: $SNAP_USER_COMMON
      #LIBGL_DEBUG: verbose
      TMPDIR: $XDG_RUNTIME_DIR
      ALWAYS_USE_PULSEAUDIO: 1
      DISABLE_WAYLAND: 1
    plugs:
      - shmem
      - desktop
      - desktop-legacy
      - wayland
      - home
      - x11
      - gsettings
      - hardware-observe
      - mount-observe
      - system-observe
      - joystick
      - network
      - opengl
      - audio-playback
      - audio-record
      - screen-inhibit-control
      - process-control
      - bluez
      - network-control
      - fuse-support
      - steam-support
      - removable-media
      - upower-observe
      - uinput
  report:
    command-chain: [bin/desktop-launch]
    command: bin/steamreport
    plugs:
      - system-observe
      - hardware-observe
      - opengl
      - x11
      - desktop
  vulkaninfo:
    command-chain: [bin/desktop-launch]
    command: bin/vulkaninfo
    plugs:
      - opengl
      - x11
      - desktop
  vkcube:
    command-chain: [bin/desktop-launch]
    command: bin/vkcube
    plugs:
      - opengl
      - x11
      - desktop
  glxinfo:
    command-chain: [bin/desktop-launch]
    command: bin/glxinfo
    plugs:
      - opengl
      - x11
      - desktop
  glxgears:
    command-chain: [bin/desktop-launch]
    command: bin/glxgears
    plugs:
      - opengl
      - x11
      - desktop
  test:
    command-chain: [bin/desktop-launch]
    command: tests/run.sh
    plugs:
      - opengl
      - x11
      - desktop
