name: steam
version: '1.0.0.85'
summary: Launcher for the Steam software distribution service
description: |
  Steam is a software distribution service with an online store, automated
  installation, automatic updates, achievements, SteamCloud synchronized
  savegame and screenshot functionality, and many social features.
adopt-info: steam
grade: stable
confinement: strict
base: core24
platforms:
  arm64:
    build-on: [arm64]
    build-for: [arm64]
compression: lzo
assumes:
  - snapd2.62

lint:
  # Snapcraft's `ldd` lint can't handle 32-bit things,
  # So just make it quiet and also make builds a surprising amount faster
  ignore:
    - library:
        - lib/i386-linux-gnu/**
        - usr/lib/i386-linux-gnu/**
        - lib32/**
        - usr/lib32/**

package-repositories:
  - type: apt
    url: http://ports.ubuntu.com/ubuntu-ports/
    suites: [noble, noble-updates]
    components: [main, universe]
    architectures: [arm64]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    key-server: keyserver.ubuntu.com
  - type: apt
    ppa: fex-emu/fex

plugs:
  gaming-graphics-core24:
    interface: content
    target: $SNAP/graphics
    default-provider: gaming-graphics-core24
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes
  dot-local-share-steam:
    interface: personal-files
    write:
      - $HOME/.local/share/Steam
      - $HOME/Steam
  dot-local-share-applications:
    interface: personal-files
    write:
      - $HOME/.local/share/applications
  dot-local-share-icons:
    interface: personal-files
    write:
      - $HOME/.local/share/icons
  desktop:
    mount-host-font-cache: false
  shmem:
    interface: shared-memory
    private: true

slots:
  steam:
    interface: dbus
    bus: session
    name: com.steampowered.PressureVessel.LaunchAlongsideSteam

hooks:
  configure:
    plugs:
      - opengl

parts:
  gaming-graphics-core24:
    plugin: nil
    build-snaps:
      - gaming-graphics-core24
  amd64-content:
    plugin: dump
    source: https://github.com/MitchellAugustin/steam-snap/releases/download/amd64-components-12-16-25.2/steam_231_amd64.tar.gz
    stage:
      - -usr/bin/curl
      - -usr/bin/fc-cache
      - -usr/bin/fc-cat
      - -usr/bin/fc-conflist
      - -usr/bin/fc-list
      - -usr/bin/fc-match
      - -usr/bin/fc-pattern
      - -usr/bin/fc-query
      - -usr/bin/fc-scan
      - -usr/bin/fc-validate
      - -usr/bin/gtk-update-icon-cache
      - -usr/bin/update-mime-database
      - -usr/bin/zenity
      - -usr/libexec/dconf-service
      - -usr/share/doc/libcups2t64/changelog.Debian.gz
      - -bin/desktop-launch
      - -usr/share/doc/libavahi-common-data/changelog.Debian.gz
    organize:
        steam_231_amd64: .
  amd64-rootfs:
    plugin: dump
    source: https://github.com/MitchellAugustin/steam-snap/releases/download/amd64-components-12-16-25.2/amd64_rootfs.tar.gz
    organize:
        amd64_rootfs: .
  fex-emu:
    plugin: nil
    stage-packages:
      - fex-emu-armv8.0
      - fex-emu-wine
      - zenity
  fex-config:
    plugin: dump
    source: ./fex_config
  wget:
    plugin: nil
    stage-packages:
      - wget
  desktop-launch:
    plugin: dump
    source: ./src/
    organize:
        desktop-launch: bin/
    stage:
      - bin/desktop-launch

  
apps:
  steam:
    command: usr/bin/fex_launcher.sh
    plugs:
      - shmem
      - camera
      - desktop
      - desktop-legacy
      - wayland
      - home
      - x11
      - gsettings
      - hardware-observe
      - mount-observe
      - system-observe
      - network-observe
      - joystick
      - network
      - network-bind
      - opengl
      - audio-playback
      - audio-record
      - screen-inhibit-control
      - process-control
      - bluez
      - network-control
      - fuse-support
      - steam-support
      - removable-media
      - upower-observe
      - uinput
      - dot-local-share-steam
